// Generated by ReScript, PLEASE EDIT WITH CARE


function itemTypeToString(itemType) {
  switch (itemType) {
    case "Book" :
      return "book";
    case "BookSection" :
      return "bookSection";
    case "JournalArticle" :
      return "journalArticle";
    case "ConferencePaper" :
      return "conferencePaper";
    case "Thesis" :
      return "thesis";
    case "Webpage" :
      return "webpage";
    case "Manuscript" :
      return "manuscript";
    case "Report" :
      return "report";
    case "Patent" :
      return "patent";
  }
}

function stringToItemType(str) {
  switch (str) {
    case "book" :
      return "Book";
    case "bookSection" :
      return "BookSection";
    case "conferencePaper" :
      return "ConferencePaper";
    case "journalArticle" :
      return "JournalArticle";
    case "manuscript" :
      return "Manuscript";
    case "patent" :
      return "Patent";
    case "report" :
      return "Report";
    case "thesis" :
      return "Thesis";
    case "webpage" :
      return "Webpage";
    default:
      return;
  }
}

function validationStateToString(state) {
  switch (state) {
    case "Valid" :
      return "VALID";
    case "Incomplete" :
      return "INCOMPLETE";
    case "Inconsistent" :
      return "INCONSISTENT";
    case "Uncertain" :
      return "UNCERTAIN";
  }
}

export {
  itemTypeToString,
  stringToItemType,
  validationStateToString,
}
/* No side effect */
