/**
 * main.js - Fogbinder Entry Point
 * Pure JavaScript wrapper for ReScript-compiled epistemic analysis engine
 *
 * Philosophy: Navigate epistemic ambiguity (late Wittgenstein + J.L. Austin)
 * NOT about removing uncertainty - about exploring it as a feature
 *
 * ⛔ NOTE: This is JavaScript, NOT TypeScript (RSR Rhodium R13 compliance)
 *         For TypeScript type definitions, use JSDoc comments
 */

// Import compiled ReScript modules
// These are generated by ReScript compiler as .bs.js files
import * as Fogbinder from './Fogbinder.bs.js';
import * as EpistemicState from './core/EpistemicState.bs.js';
import * as SpeechAct from './core/SpeechAct.bs.js';
import * as FogTrailVisualizer from './engine/FogTrailVisualizer.bs.js';

/**
 * @typedef {Object} AnalysisResult
 * @property {Array} contradictions
 * @property {Array} moods
 * @property {Array} mysteries
 * @property {Object} fogTrail
 * @property {Object} metadata
 * @property {number} metadata.analyzed
 * @property {number} metadata.totalSources
 * @property {number} metadata.totalContradictions
 * @property {number} metadata.totalMysteries
 * @property {number} metadata.overallOpacity
 */

/**
 * @typedef {Object} LanguageGame
 * @property {string} domain
 * @property {string[]} conventions
 * @property {string[]} participants
 * @property {string} purpose
 */

/**
 * Main analysis function - analyzes array of source texts
 * @param {string[]} sources - Array of citation texts to analyze
 * @param {LanguageGame} context - Language game context (domain, conventions, etc.)
 * @returns {AnalysisResult} Analysis result with contradictions, moods, mysteries, FogTrail
 */
export function analyze(sources, context) {
  return Fogbinder.analyze(sources, context, undefined);
}

/**
 * Analyze a Zotero collection by ID
 * @param {string} collectionId - Zotero collection identifier
 * @returns {Promise<AnalysisResult>} Promise resolving to analysis result
 */
export async function analyzeZoteroCollection(collectionId) {
  return await Fogbinder.analyzeZoteroCollection(collectionId);
}

/**
 * Generate human-readable report from analysis
 * @param {AnalysisResult} result - Analysis result
 * @returns {string} Markdown-formatted report
 */
export function generateReport(result) {
  return Fogbinder.generateReport(result);
}

/**
 * Export analysis to JSON
 * @param {AnalysisResult} result - Analysis result
 * @returns {Object} JSON representation
 */
export function toJson(result) {
  return Fogbinder.toJson(result);
}

/**
 * Generate SVG visualization of FogTrail
 * @param {AnalysisResult} result - Analysis result
 * @param {number} [width=1000] - Canvas width
 * @param {number} [height=800] - Canvas height
 * @returns {string} SVG string
 */
export function generateVisualization(result, width = 1000, height = 800) {
  return FogTrailVisualizer.toSvg(result.fogTrail, width, height, undefined);
}

// Default export
export default {
  analyze,
  analyzeZoteroCollection,
  generateReport,
  toJson,
  generateVisualization,
};

// Example usage (commented out)
/*
const sources = [
  "The meaning of a word is its use in the language.",
  "Philosophical problems arise when language goes on holiday.",
  "Meaning is determined by truth conditions.",
];

const context = {
  domain: "Philosophy of Language",
  conventions: ["academic discourse", "analytic tradition"],
  participants: ["philosophers", "linguists"],
  purpose: "Understanding meaning",
};

const result = analyze(sources, context);
console.log(generateReport(result));
console.log("FogTrail opacity:", result.metadata.overallOpacity);
*/
