# Module manifest for module 'ZoteroReScriptTemplater'
# Generated by: Zotero ReScript Templater Project
# Generated on: 2024-11-22

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'init-zotero-rscript-plugin.ps1'

    # Version number of this module.
    ModuleVersion = '0.2.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core', 'Desktop')

    # ID used to uniquely identify this module
    GUID = '8f3a9c2b-4d5e-6f7a-8b9c-0d1e2f3a4b5c'

    # Author of this module
    Author = 'Zotero ReScript Templater Contributors'

    # Company or vendor of this module
    CompanyName = 'Open Source'

    # Copyright statement for this module
    Copyright = '(c) 2024 Zotero ReScript Templater Contributors. Licensed under AGPL-3.0-only.'

    # Description of the functionality provided by this module
    Description = @'
A comprehensive scaffolding system for creating Zotero plugins with type-safe,
memory-safe, and offline-first architecture. Implements the Rhodium Standard
Repository (RSR) framework and provides three template types (Practitioner,
Researcher, Student) with full CI/CD infrastructure, testing, and documentation.

Key Features:
- Three production-ready template types for different use cases
- Type-safe code generation (ReScript, TypeScript)
- File integrity verification with XXHash64
- Cross-platform support (Windows, Linux, macOS)
- Comprehensive testing (70+ tests)
- CI/CD automation (GitHub Actions)
- RSR framework compliance (Platinum level - 91%+)
- TPCF graduated trust model for governance
- Offline-first architecture (no network dependencies)

Templates:
- Practitioner: ReScript/ReasonML with bootstrap.js and XUL overlays
- Researcher: Citation analysis with SQLite database integration
- Student: TypeScript educational template with comprehensive tutorial
'@

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.0'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('New-ZoteroPlugin', 'Test-ZoteroPluginIntegrity')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList = @(
        'init-zotero-rscript-plugin.ps1',
        'init-raczotbuild.rkt',
        'init-zotero-plugin.sh',
        'zotero-template-dependencies.ps1',
        'README.md',
        'LICENSE',
        'CHANGELOG.md',
        'CONTRIBUTING.md',
        'CODE_OF_CONDUCT.md',
        'SECURITY.md',
        'MAINTAINERS.md',
        'RSR_COMPLIANCE.md',
        'TPCF.md',
        'CITATION.cff'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @(
                'Zotero',
                'Plugin',
                'Scaffolding',
                'CodeGeneration',
                'ReScript',
                'TypeScript',
                'Template',
                'RSR',
                'TPCF',
                'OfflineFirst',
                'TypeSafety',
                'MemorySafety',
                'CI-CD',
                'Testing',
                'Research',
                'Academia',
                'CrossPlatform',
                'PowerShell7',
                'Linux',
                'macOS',
                'Windows'
            )

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/Hyperpolymath/zotero-rescript-templater/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Hyperpolymath/zotero-rescript-templater'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
## [0.2.0] - 2024-11-22

### Added
- Complete XXHash64 implementation for file integrity verification
- Three production-ready Zotero plugin templates (Practitioner, Researcher, Student)
- Comprehensive testing infrastructure (70+ tests across PowerShell and Racket)
- Cross-platform Bash scaffolder for Linux/macOS
- CI/CD pipelines with GitHub Actions (Windows, Linux, macOS)
- RSR framework compliance (Platinum level - 91%+)
- TPCF governance model with tri-perimeter access control
- .well-known directory with RFC 9116 compliant security.txt
- Academic citation support (CITATION.cff)
- Nix flakes for reproducible builds
- justfile with 40+ build automation recipes
- Property-based testing with QuickCheck-style tests
- Comprehensive documentation suite

### Changed
- Upgraded from placeholder templates to full working Zotero plugins
- Enhanced file integrity system with production-grade hashing
- Improved cross-platform compatibility

### Fixed
- XXHash64 implementation now production-ready (replaced placeholder)
- Template variable substitution handles edge cases correctly
- File permissions properly set on Linux/macOS

See CHANGELOG.md for full release history.
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $true

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI = 'https://github.com/Hyperpolymath/zotero-rescript-templater/blob/main/README.md'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
